### ISSUE TITLE
userdata

### ISSUE THREAD

**Issue by StarBalll** [oliver-zehentleitner/unicorn-fy#22]
# def binance_futures_websocket
# ->>
# line 577
            elif stream_data['e'] == 'ORDER_TRADE_UPDATE':
                stream_data = {'data': stream_data}
            elif stream_data['e'] == 'ACCOUNT_UPDATE':
                stream_data = {'data': stream_data}

# line             elif stream_data['data']['e'] == 'executionReport': #next 
           elif stream_data['data']['e'] == 'ORDER_TRADE_UPDATE':
                print('这里是发现了订单推送')
                unicorn_fied_data = {'stream_type': 'ORDER_TRADE_UPDATE',
                                     'event_type': stream_data['data']['e'],
                                     'event_time': stream_data['data']['E'],
                                     'symbol': stream_data['data']['o']['s'], # 交易对
                                     'client_order_id': stream_data['data']['o']['c'], # 订单编号
                                     'side': stream_data['data']['o']['S'], # 有用,订单方向
                                     'order_type': stream_data['data']['o']['o'], # 订单类型
                                     'time_in_force': stream_data['data']['o']['f'], # 有效方式
                                     'order_quantity': stream_data['data']['o']['q'], # 订单原始数量
                                     'order_price': stream_data['data']['o']['p'],# 原始价格
                                     'order_avg_price': stream_data['data']['o']['ap'],# 平均价格
                                     'order_tj_price': stream_data['data']['o']['sp'],# 条件订单触发价格，对追踪止损单无效
                                     'current_execution_type': stream_data['data']['o']['x'],# 本次事件的具体执行类型
                                     'current_order_status': stream_data['data']['o']['X'], # 订单的当前状态
                                     'order_id': stream_data['data']['o']['i'],# 订单ID
                                     'last_executed_quantity': stream_data['data']['o']['l'],# 订单末次成交量
                                     'cumulative_filled_quantity': stream_data['data']['o']['z'],# 订单累计已成交量
                                     'last_executed_price': stream_data['data']['o']['L'],# 订单末次成交价格
                                     # 'commission_amount': stream_data['data']['o']['n'],# 手续费数量
                                     # 'commission_asset': stream_data['data']['o']['N'],# 手续费资产类型
                                     'transaction_time': stream_data['data']['o']['T'],# 成交时间
                                     'trade_id': stream_data['data']['o']['t'], # 成交ID
                                     'net_pay': stream_data['data']['o']['b'], # 买单净值
                                     'net_selling_order_value': stream_data['data']['o']['a'],# 卖单净值
                                     'is_trade_maker_side': stream_data['data']['o']['m'], # 该成交是作为挂单成交吗
                                     'reduceOnly': stream_data['data']['o']['R'],# 是否是只减仓单
                                     'trigger_price_type': stream_data['data']['o']['wt'], # 触发价类型
                                     'order_price_type': stream_data['data']['o']['ot'],# 原始定单类型
                                     'positionSide': stream_data['data']['o']['ps'],
                                     # 'cumulative_quote_asset_transacted_quantity': stream_data['data']['cp'],
                                     # 'cumulative_quote_asset_transacted_quantity': stream_data['data']['AP'],
                                     # 'cumulative_quote_asset_transacted_quantity': stream_data['data']['cr'],
                                     'order_profit_loss': stream_data['data']['o']['rp']} #该交易实现盈亏

**Comment by StarBalll** [comment]
https://binance-docs.github.io/apidocs/futures/en/#event-order-update

This is futures

Push analysis of order information

**Comment by oliver-zehentleitner** [comment]
If you have the code ready, do you want to make a pull request? This will add you to contributors list :)

**Comment by oliver-zehentleitner** [comment]
and one example of received raw data of this event for the test unit would be nice too!
thanks you!

**Comment by StarBalll** [comment]
我不太会用git哈.你看着写吧哈.还有另外一个帐号信息推送的我就不会了...
I don't know how to use GIT. You can write it. There is another account information push, I won't

https://binance-docs.github.io/apidocs/futures/en/#event-balance-and-position-update


"e": "ACCOUNT_UPDATE",                // Event Type

**Comment by oliver-zehentleitner** [comment]
its not hard to do that. just create a fork, edit the fork and when its ready click pull request.

Here is a step by step description: https://www.dataschool.io/how-to-contribute-on-github/
