### ISSUE TITLE
Complete ACCOUNT_UPDATE event for binance futures

### ISSUE THREAD

**Issue by folktale42** [oliver-zehentleitner/unicorn-fy#27]
**Is your feature request related to a problem? Please describe.**

The account data is not being parsed on the ACCOUNT_UPDATE event of binance futures.

**Describe the solution you'd like**

Implement the missing sections.

**Describe alternatives you've considered**

**Additional context**

**Comment by oliver-zehentleitner** [comment]
Thank you very much!
Your PR is released with 0.11.0: https://github.com/oliver-zehentleitner/unicorn-fy/releases/tag/0.11.0
Best regards!
